#include "driverlib.h"
#include "device.h"
#include "Ai_CLLLC_ADC_settings.h"



void clc_HAL_setADC(void)
{

    //ADC_setVREF(ADCA_BASE, ADC_REFERENCE_INTERNAL, ADC_REFERENCE_3_3V);
    //ADC_setVREF(ADCB_BASE, ADC_REFERENCE_INTERNAL, ADC_REFERENCE_3_3V);
    //ADC_setVREF(ADCC_BASE, ADC_REFERENCE_INTERNAL, ADC_REFERENCE_3_3V);

    ADC_setPrescaler(ADCA_BASE, ADC_CLK_DIV_2_0);
    ADC_setPrescaler(ADCB_BASE, ADC_CLK_DIV_2_0);
    ADC_setPrescaler(ADCC_BASE, ADC_CLK_DIV_2_0);

    ADC_enableConverter(ADCA_BASE);
    ADC_enableConverter(ADCB_BASE);
    ADC_enableConverter(ADCC_BASE);

    DEVICE_DELAY_US(1000);

    // VPRIM
    ADC_setupSOC(CLC_VPRIM_ADC_MODULE, CLC_VPRIM_ADC_SOC_NO_0, CLC_VPRIM_ADC_TRIG_SOURCE, CLC_VPRIM_ADC_PIN, CLC_VPRIM_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_VPRIM_ADC_MODULE, CLC_VPRIM_ADC_SOC_NO_1, CLC_VPRIM_ADC_TRIG_SOURCE, CLC_VPRIM_ADC_PIN, CLC_VPRIM_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_VPRIM_ADC_MODULE, CLC_VPRIM_ADC_SOC_NO_2, CLC_VPRIM_ADC_TRIG_SOURCE, CLC_VPRIM_ADC_PIN, CLC_VPRIM_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_VPRIM_ADC_MODULE, CLC_VPRIM_ADC_SOC_NO_3, CLC_VPRIM_ADC_TRIG_SOURCE, CLC_VPRIM_ADC_PIN, CLC_VPRIM_ADC_ACQPS_SYS_CLKS);

    ADC_setupSOC(CLC_IPRIM_TANK_ADC_MODULE, CLC_IPRIM_TANK_ADC_SOC_NO_4, CLC_IPRIM_TANK_ADC_TRIG_SOURCE, CLC_IPRIM_TANK_ADC_PIN, CLC_IPRIM_TANK_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_IPRIM_TANK_ADC_MODULE, CLC_IPRIM_TANK_ADC_SOC_NO_5, CLC_IPRIM_TANK_ADC_TRIG_SOURCE, CLC_IPRIM_TANK_ADC_PIN, CLC_IPRIM_TANK_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_IPRIM_TANK_ADC_MODULE, CLC_IPRIM_TANK_ADC_SOC_NO_6, CLC_IPRIM_TANK_ADC_TRIG_SOURCE, CLC_IPRIM_TANK_ADC_PIN, CLC_IPRIM_TANK_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_IPRIM_TANK_ADC_MODULE, CLC_IPRIM_TANK_ADC_SOC_NO_7, CLC_IPRIM_TANK_ADC_TRIG_SOURCE, CLC_IPRIM_TANK_ADC_PIN, CLC_IPRIM_TANK_ADC_ACQPS_SYS_CLKS);

    ADC_setupSOC(CLC_VSEC_ADC_MODULE, CLC_VSEC_ADC_SOC_NO_0, CLC_VSEC_ADC_TRIG_SOURCE, CLC_VSEC_ADC_PIN, CLC_VSEC_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_VSEC_ADC_MODULE, CLC_VSEC_ADC_SOC_NO_1, CLC_VSEC_ADC_TRIG_SOURCE, CLC_VSEC_ADC_PIN, CLC_VSEC_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_VSEC_ADC_MODULE, CLC_VSEC_ADC_SOC_NO_2, CLC_VSEC_ADC_TRIG_SOURCE, CLC_VSEC_ADC_PIN, CLC_VSEC_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_VSEC_ADC_MODULE, CLC_VSEC_ADC_SOC_NO_3, CLC_VSEC_ADC_TRIG_SOURCE, CLC_VSEC_ADC_PIN, CLC_VSEC_ADC_ACQPS_SYS_CLKS);

    ADC_setupSOC(CLC_ISEC_ADC_MODULE, CLC_ISEC_ADC_SOC_NO_4, CLC_ISEC_ADC_TRIG_SOURCE, CLC_ISEC_ADC_PIN, CLC_ISEC_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_ISEC_ADC_MODULE, CLC_ISEC_ADC_SOC_NO_5, CLC_ISEC_ADC_TRIG_SOURCE, CLC_ISEC_ADC_PIN, CLC_ISEC_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_ISEC_ADC_MODULE, CLC_ISEC_ADC_SOC_NO_6, CLC_ISEC_ADC_TRIG_SOURCE, CLC_ISEC_ADC_PIN, CLC_ISEC_ADC_ACQPS_SYS_CLKS);
    ADC_setupSOC(CLC_ISEC_ADC_MODULE, CLC_ISEC_ADC_SOC_NO_7, CLC_ISEC_ADC_TRIG_SOURCE, CLC_ISEC_ADC_PIN, CLC_ISEC_ADC_ACQPS_SYS_CLKS);

    ADC_setupSOC(CLC_FanSpd_ADC_MODULE, CLC_FanSpd_ADC_SOC_NO_0, CLC_FanSpd_ADC_TRIG_SOURCE, CLC_FanSpd_ADC_PIN, CLC_FanSpd_ADC_ACQPS_SYS_CLKS);

    ADC_setupSOC(CLC_NTC_ADC_MODULE, CLC_NTC_ADC_SOC_NO_1, CLC_NTC_ADC_TRIG_SOURCE, CLC_NTC_ADC_PIN, CLC_NTC_ADC_ACQPS_SYS_CLKS);

    ADC_setupSOC(CLC_Vreal_ADC_MODULE, CLC_Vreal_ADC_SOC_NO_2, CLC_Vreal_ADC_TRIG_SOURCE, CLC_Vreal_ADC_PIN, CLC_Vreal_ADC_ACQPS_SYS_CLKS);

   // setup another slow ADC conversion for ISR3 trigger

/*
        ADC_setupSOC(CLC_THBUS_ADC_MODULE,
                     CLC_THBUS_ADC_SOC_NO_13,
                     CLC_ADC_TRIG_SLOW_SOURCE,
                     CLC_THBUS_ADC_PIN,
                     CLC_THBUS_ADC_ACQPS_SYS_CLKS);

        ADC_setupSOC(CLC_TH_HV_ADC_MODULE,
                     CLC_TH_HV_ADC_SOC_NO_14,
                     CLC_ADC_TRIG_SLOW_SOURCE,
                     CLC_TH_HV_ADC_PIN,
                     CLC_TH_HV_ADC_ACQPS_SYS_CLKS);
*/
}
