#ifndef AI_CLLLC_ADC_SETTINGS_H_
#define AI_CLLLC_ADC_SETTINGS_H_

#define CLC_ADC_TRIG_SOURCE ADC_TRIGGER_EPWM10_SOCA //ADC_TRIGGER_EPWM5_SOCA
#define CLC_ADC_TRIG_SLOW_SOURCE ADC_TRIGGER_CPU1_TINT2

//---------------start to configure ADC channels---------------
//ADC-A2, CMPIN1P, primary side (input) voltage
#define CLC_VPRIM_ADC_MODULE      ADCA_BASE
#define CLC_VPRIM_ADC_PIN         ADC_CH_ADCIN2
#define CLC_VPRIM_ADC_TRIG_SOURCE CLC_ADC_TRIG_SOURCE
#define CLC_VPRIM_ADC_ACQPS_SYS_CLKS 30
#define CLC_VPRIM_ADCRESULTREGBASE ADCARESULT_BASE

#define CLC_VPRIM_ADC_SOC_NO_0  ADC_SOC_NUMBER0
#define CLC_VPRIM_ADC_SOC_NO_1  ADC_SOC_NUMBER1
#define CLC_VPRIM_ADC_SOC_NO_2  ADC_SOC_NUMBER2
#define CLC_VPRIM_ADC_SOC_NO_3  ADC_SOC_NUMBER3
#define CLC_VPRIM_ADCREAD_0 ADC_readResult(CLC_VPRIM_ADCRESULTREGBASE, CLC_VPRIM_ADC_SOC_NO_0)
#define CLC_VPRIM_ADCREAD_1 ADC_readResult(CLC_VPRIM_ADCRESULTREGBASE, CLC_VPRIM_ADC_SOC_NO_1)
#define CLC_VPRIM_ADCREAD_2 ADC_readResult(CLC_VPRIM_ADCRESULTREGBASE, CLC_VPRIM_ADC_SOC_NO_2)
#define CLC_VPRIM_ADCREAD_3 ADC_readResult(CLC_VPRIM_ADCRESULTREGBASE, CLC_VPRIM_ADC_SOC_NO_3)

#define CLC_VPRIM_ADCREAD (CLC_VPRIM_ADCREAD_0)
#define CLC_VPRIM_OV_SAMPLE_ADC ((CLC_VPRIM_ADCREAD_0 + CLC_VPRIM_ADCREAD_1 + CLC_VPRIM_ADCREAD_2 + CLC_VPRIM_ADCREAD_3) * 0.25F)

//ADC-A4, CMPIN2P, primary tank current
#define CLC_IPRIM_TANK_ADC_MODULE    ADCA_BASE
#define CLC_IPRIM_TANK_ADC_PIN             ADC_CH_ADCIN4      // Modify it to ADC channel 2, disable PGA
#define CLC_IPRIM_TANK_ADC_TRIG_SOURCE     CLC_ADC_TRIG_SOURCE
#define CLC_IPRIM_TANK_ADC_ACQPS_SYS_CLKS  30
#define CLC_IPRIM_TANK_ADCRESULTREGBASE    ADCARESULT_BASE

#define CLC_IPRIM_TANK_ADC_SOC_NO_4  ADC_SOC_NUMBER4
#define CLC_IPRIM_TANK_ADC_SOC_NO_5  ADC_SOC_NUMBER5
#define CLC_IPRIM_TANK_ADC_SOC_NO_6  ADC_SOC_NUMBER6
#define CLC_IPRIM_TANK_ADC_SOC_NO_7  ADC_SOC_NUMBER7
#define CLC_IPRIM_TANK_ADCREAD_4 ADC_readResult(CLC_IPRIM_TANK_ADCRESULTREGBASE, CLC_IPRIM_TANK_ADC_SOC_NO_4)
#define CLC_IPRIM_TANK_ADCREAD_5 ADC_readResult(CLC_IPRIM_TANK_ADCRESULTREGBASE, CLC_IPRIM_TANK_ADC_SOC_NO_5)
#define CLC_IPRIM_TANK_ADCREAD_6 ADC_readResult(CLC_IPRIM_TANK_ADCRESULTREGBASE, CLC_IPRIM_TANK_ADC_SOC_NO_6)
#define CLC_IPRIM_TANK_ADCREAD_7 ADC_readResult(CLC_IPRIM_TANK_ADCRESULTREGBASE, CLC_IPRIM_TANK_ADC_SOC_NO_7)

#define CLC_IPRIM_TANK_ADCREAD (CLC_IPRIM_TANK_ADCREAD_4)
#define CLC_IPRIM_TANK_OV_SAMPLE_ADC ((CLC_IPRIM_TANK_ADCREAD_4 + CLC_IPRIM_TANK_ADCREAD_5 + CLC_IPRIM_TANK_ADCREAD_6 + CLC_IPRIM_TANK_ADCREAD_7 ) * (0.25F))

//ADC-C4, CMPIN5P, secondary side bus voltage
#define CLC_VSEC_ADC_MODULE  ADCC_BASE
#define CLC_VSEC_ADC_PIN     ADC_CH_ADCIN4
#define CLC_VSEC_ADC_TRIG_SOURCE CLC_ADC_TRIG_SOURCE
#define CLC_VSEC_ADC_ACQPS_SYS_CLKS 30
#define CLC_VSEC_ADCRESULTREGBASE ADCARESULT_BASE

#define CLC_VSEC_ADC_SOC_NO_0  ADC_SOC_NUMBER0
#define CLC_VSEC_ADC_SOC_NO_1  ADC_SOC_NUMBER1
#define CLC_VSEC_ADC_SOC_NO_2  ADC_SOC_NUMBER2  // Vsec output 0 ~ 850V
#define CLC_VSEC_ADC_SOC_NO_3  ADC_SOC_NUMBER3

#define CLC_VSEC_ADCREAD_0 ADC_readResult(CLC_VSEC_ADCRESULTREGBASE, CLC_VSEC_ADC_SOC_NO_0)
#define CLC_VSEC_ADCREAD_1 ADC_readResult(CLC_VSEC_ADCRESULTREGBASE, CLC_VSEC_ADC_SOC_NO_1)
#define CLC_VSEC_ADCREAD_2 ADC_readResult(CLC_VSEC_ADCRESULTREGBASE, CLC_VSEC_ADC_SOC_NO_2)
#define CLC_VSEC_ADCREAD_3 ADC_readResult(CLC_VSEC_ADCRESULTREGBASE, CLC_VSEC_ADC_SOC_NO_3)

#define CLC_VSEC_ADCREAD (CLC_VSEC_ADCREAD_0)
#define CLC_VSEC_OV_SAMPLE_ADC ((CLC_VSEC_ADCREAD_0 + CLC_VSEC_ADCREAD_1 + CLC_VSEC_ADCREAD_2 + CLC_VSEC_ADCREAD_3) * (0.25F))

//ADC-C2, CMPIN6P, secondary side bus current
#define CLC_ISEC_ADC_MODULE  ADCC_BASE
#define CLC_ISEC_ADC_PIN     ADC_CH_ADCIN2
#define CLC_ISEC_ADC_TRIG_SOURCE CLC_ADC_TRIG_SOURCE
#define CLC_ISEC_ADC_ACQPS_SYS_CLKS 30
#define CLC_ISEC_ADCRESULTREGBASE ADCCRESULT_BASE

#define CLC_ISEC_ADC_SOC_NO_4  ADC_SOC_NUMBER4
#define CLC_ISEC_ADC_SOC_NO_5  ADC_SOC_NUMBER5
#define CLC_ISEC_ADC_SOC_NO_6  ADC_SOC_NUMBER6
#define CLC_ISEC_ADC_SOC_NO_7  ADC_SOC_NUMBER7

#define CLC_ISEC_ADCREAD_4 ADC_readResult(CLC_ISEC_ADCRESULTREGBASE, CLC_ISEC_ADC_SOC_NO_4)
#define CLC_ISEC_ADCREAD_5 ADC_readResult(CLC_ISEC_ADCRESULTREGBASE, CLC_ISEC_ADC_SOC_NO_5)
#define CLC_ISEC_ADCREAD_6 ADC_readResult(CLC_ISEC_ADCRESULTREGBASE, CLC_ISEC_ADC_SOC_NO_6)
#define CLC_ISEC_ADCREAD_7 ADC_readResult(CLC_ISEC_ADCRESULTREGBASE, CLC_ISEC_ADC_SOC_NO_7)

#define CLC_ISEC_ADCREAD (CLC_ISEC_ADCREAD_4)
#define CLC_ISEC_OV_SAMPLE_ADC ((CLC_ISEC_ADCREAD_4 + CLC_ISEC_ADCREAD_5 + CLC_ISEC_ADCREAD_6 + CLC_ISEC_ADCREAD_7) * (0.25F))

//ADC-D0, CMPIN7P, Fan speed
#define CLC_FanSpd_ADC_MODULE  ADCD_BASE
#define CLC_FanSpd_ADC_PIN     ADC_CH_ADCIN0
#define CLC_FanSpd_ADC_TRIG_SOURCE CLC_ADC_TRIG_SOURCE
#define CLC_FanSpd_ADC_ACQPS_SYS_CLKS 30
#define CLC_FanSpd_ADCRESULTREGBASE ADCDRESULT_BASE

#define CLC_FanSpd_ADC_SOC_NO_0  ADC_SOC_NUMBER0
#define CLC_FanSpd_ADCREAD_0 ADC_readResult(CLC_FanSpd_ADCRESULTREGBASE, CLC_FanSpd_ADC_SOC_NO_0)

//ADC-D2, CMPIN8P, NTC (thermal sensor)
#define CLC_NTC_ADC_MODULE  ADCD_BASE
#define CLC_NTC_ADC_PIN     ADC_CH_ADCIN2
#define CLC_NTC_ADC_TRIG_SOURCE CLC_ADC_TRIG_SOURCE
#define CLC_NTC_ADC_ACQPS_SYS_CLKS 30
#define CLC_NTC_ADCRESULTREGBASE ADCDRESULT_BASE

#define CLC_NTC_ADC_SOC_NO_1  ADC_SOC_NUMBER1
#define CLC_NTC_ADCREAD_1 ADC_readResult(CLC_NTC_ADCRESULTREGBASE, CLC_NTC_ADC_SOC_NO_1)

//ADC-D1, real voltage (output voltage), without protection
#define CLC_Vreal_ADC_MODULE  ADCD_BASE
#define CLC_Vreal_ADC_PIN     ADC_CH_ADCIN1
#define CLC_Vreal_ADC_TRIG_SOURCE CLC_ADC_TRIG_SOURCE
#define CLC_Vreal_ADC_ACQPS_SYS_CLKS 30
#define CLC_Vreal_ADCRESULTREGBASE ADCDRESULT_BASE

#define CLC_Vreal_ADC_SOC_NO_2  ADC_SOC_NUMBER2
#define CLC_Vreal_ADCREAD_2 ADC_readResult(CLC_ISEC_ADCRESULTREGBASE, CLC_ISEC_ADC_SOC_NO_2)


#endif /* AI_CLLLC_ADC_SETTINGS_H_ */
