#include "clllc.h"

void clc_HAL_setProtect()
{
    // Disable all the muxes first
    XBAR_disableEPWMMux(XBAR_TRIP4, 0xFF);
/*
#if CLC_BOARD_PROTECTION_IPRIM == 1

    CLC_HAL_setupCMPSS(CLC_IPRIM_CMPSS_BASE, CLC_IPRIM_TRIP_LIMIT_AMPS, CLC_IPRIM_MAX_SENSE_AMPS);

    XBAR_setEPWMMuxConfig(XBAR_TRIP4, CLC_IPRIM_XBAR_MUX_VAL);
    XBAR_enableEPWMMux(XBAR_TRIP4, CLC_IPRIM_XBAR_MUX);

    XBAR_clearInputFlag(CLC_IPRIM_CMPSS_XBAR_FLAG1);
    XBAR_clearInputFlag(CLC_IPRIM_CMPSS_XBAR_FLAG2);
#else
    #warning BOARD_PROTECTION_IPRIM is disabled
#endif
*/
#if CLC_BOARD_PROTECTION_IPRIM_TANK == 1

    CLC_HAL_setupCMPSS(CLC_IPRIM_TANK_CMPSS_BASE, CLC_IPRIM_TANK_TRIP_LIMIT_AMPS, CLC_IPRIM_TANK_MAX_SENSE_AMPS);

//    clc_Hal_setIPRMtankCmpss_HighLowLim(CLC_IPRIM_TANK_CMPSS_BASE, CLC_IPRIM_TANK_TRIP_LIMIT_AMPS, CLC_IPRIM_TANK_MAX_SENSE_AMPS,
//                                        CLC_CMPSS_HYSTERESIS, CLC_CMPSSS_FILTER_PRESCALAR, CLC_CMPSS_WINODW, CLC_CMPSS_THRESHOLD);

    XBAR_setEPWMMuxConfig(XBAR_TRIP4, CLC_IPRIM_TANK_CMPSS_XBAR_MUX_VAL);
    XBAR_enableEPWMMux(XBAR_TRIP4, CLC_IPRIM_TANK_CMPSS_XBAR_MUX);
    XBAR_clearInputFlag(CLC_IPRIM_TANK_CMPSS_XBAR_FLAG1);
    XBAR_clearInputFlag(CLC_IPRIM_TANK_CMPSS_XBAR_FLAG2);
#else
    #warning BOARD_PROTECTION_IPRIM_TANK is disabled
#endif

#if CLC_BOARD_PROTECTION_ISEC == 1
    CLC_HAL_setupCMPSS(CLC_ISEC_CMPSS_BASE, CLC_ISEC_TRIP_LIMIT_AMPS, CLC_ISEC_MAX_SENSE_AMPS);
    XBAR_setEPWMMuxConfig(XBAR_TRIP4, CLC_ISEC_XBAR_MUX_VAL);
    XBAR_enableEPWMMux(XBAR_TRIP4, CLC_ISEC_XBAR_MUX);
    XBAR_clearInputFlag(CLC_ISEC_CMPSS_XBAR_FLAG1);
    XBAR_clearInputFlag(CLC_ISEC_CMPSS_XBAR_FLAG2);
#else
    #warning BOARD_PROTECTION_ISEC is disabled
#endif

#if CLC_BOARD_PROTECTION_VPRIM == 1
    clc_Hal_setCmpss_HighLowVoltLim(CLC_VPRIM_CMPSS_BASE, CLC_VPRIM_TRIP_LIMIT_VOLT, 0, CLC_VPRIM_MAX_SENSE_VOLTS,
                                    2, 2, 30, 20);

//    CLC_HAL_setupCMPSS(CLC_VPRIM_CMPSS_BASE, CLC_VPRIM_TRIP_LIMIT_VOLT, CLC_VPRIM_MAX_SENSE_VOLTS);
    XBAR_setEPWMMuxConfig(XBAR_TRIP4, CLC_VPRIM_CMPSS_XBAR_MUX_VAL);
    XBAR_enableEPWMMux(XBAR_TRIP4, CLC_VPRIM_CMPSS_XBAR_MUX);
    XBAR_clearInputFlag(CLC_VPRIM_CMPSS_XBAR_FLAG1);
//    XBAR_clearInputFlag(CLC_VPRIM_CMPSS_XBAR_FLAG2);
#else
    #warning BOARD_PROTECTION_VPRIM is disabled
#endif

#if CLC_BOARD_PROTECTION_VSEC == 1
    clc_Hal_setCmpss_HighLowVoltLim(CLC_VSEC_CMPSS_BASE, CLC_VSEC_TRIP_LIMIT_VOLT, 0, CLC_VSEC_MAX_SENSE_VOLTS,
                                    2, 2, 30, 20);
    XBAR_setEPWMMuxConfig(XBAR_TRIP4, CLC_VSEC_CMPSS_XBAR_MUX_VAL);
    XBAR_enableEPWMMux(XBAR_TRIP4, CLC_VSEC_CMPSS_XBAR_MUX);
    XBAR_clearInputFlag(CLC_VSEC_CMPSS_XBAR_FLAG1);
//    XBAR_clearInputFlag(CLC_VSEC_CMPSS_XBAR_FLAG2);

#else
    #warning BOARD_PROTECTION_VSEC is disabled
#endif

#if CLC_BOARD_PROTECTION_IPRIM_TANK == 1 || CLC_BOARD_PROTECTION_VSEC == 1 || CLC_BOARD_PROTECTION_ISEC == 1 || CLC_BOARD_PROTECTION_VPRIM == 1

    //Trip 4 is the input to the DCAHCOMPSEL
    EPWM_selectDigitalCompareTripInput(CLC_PRIM_LEG1_PWM_BASE, EPWM_DC_TRIP_TRIPIN4, EPWM_DC_TYPE_DCAH);
    EPWM_setTripZoneDigitalCompareEventCondition(CLC_PRIM_LEG1_PWM_BASE, EPWM_TZ_DC_OUTPUT_A1, EPWM_TZ_EVENT_DCXH_HIGH);
    EPWM_setDigitalCompareEventSource(CLC_PRIM_LEG1_PWM_BASE, EPWM_DC_MODULE_A, EPWM_DC_EVENT_1, EPWM_DC_EVENT_SOURCE_ORIG_SIGNAL);
    EPWM_setDigitalCompareEventSyncMode(CLC_PRIM_LEG1_PWM_BASE, EPWM_DC_MODULE_A, EPWM_DC_EVENT_1, EPWM_DC_EVENT_INPUT_NOT_SYNCED);

    EPWM_selectDigitalCompareTripInput(CLC_SEC_LEG1_PWM_BASE, EPWM_DC_TRIP_TRIPIN4, EPWM_DC_TYPE_DCAH);
    EPWM_setTripZoneDigitalCompareEventCondition(CLC_SEC_LEG1_PWM_BASE, EPWM_TZ_DC_OUTPUT_A1, EPWM_TZ_EVENT_DCXH_HIGH);
    EPWM_setDigitalCompareEventSource(CLC_SEC_LEG1_PWM_BASE, EPWM_DC_MODULE_A, EPWM_DC_EVENT_1, EPWM_DC_EVENT_SOURCE_ORIG_SIGNAL);
    EPWM_setDigitalCompareEventSyncMode(CLC_SEC_LEG1_PWM_BASE, EPWM_DC_MODULE_A , EPWM_DC_EVENT_1, EPWM_DC_EVENT_INPUT_NOT_SYNCED);

    // Enable the following trips Emulator Stop, TZ1-3 and DCAEVT1
    EPWM_enableTripZoneSignals(CLC_PRIM_LEG1_PWM_BASE, EPWM_TZ_SIGNAL_DCAEVT1);
    EPWM_enableTripZoneSignals(CLC_SEC_LEG1_PWM_BASE, EPWM_TZ_SIGNAL_DCAEVT1);

#else
    #warning All current comparator based protections are disabled
#endif

    // TZA events can force EPWMxA
    // TZB events can force EPWMxB
    EPWM_setTripZoneAction(CLC_PRIM_LEG1_PWM_BASE, EPWM_TZ_ACTION_EVENT_TZA, EPWM_TZ_ACTION_LOW);
    EPWM_setTripZoneAction(CLC_PRIM_LEG1_PWM_BASE, EPWM_TZ_ACTION_EVENT_TZB, EPWM_TZ_ACTION_LOW);

    EPWM_setTripZoneAction(CLC_SEC_LEG1_PWM_BASE, EPWM_TZ_ACTION_EVENT_TZA, EPWM_TZ_ACTION_LOW);
    EPWM_setTripZoneAction(CLC_SEC_LEG1_PWM_BASE, EPWM_TZ_ACTION_EVENT_TZB, EPWM_TZ_ACTION_LOW);

    EPWM_clearCycleByCycleTripZoneFlag(CLC_PRIM_LEG1_PWM_BASE, EPWM_TZ_CBC_FLAG_1);
    EPWM_clearCycleByCycleTripZoneFlag(CLC_SEC_LEG1_PWM_BASE, EPWM_TZ_CBC_FLAG_1);

    // Clear any spurious trip
    EPWM_clearTripZoneFlag (CLC_PRIM_LEG1_PWM_BASE, EPWM_TZ_FLAG_DCAEVT1);
    EPWM_clearTripZoneFlag(CLC_SEC_LEG1_PWM_BASE, EPWM_TZ_FLAG_DCAEVT1);

    EPWM_forceTripZoneEvent(CLC_PRIM_LEG1_PWM_BASE, EPWM_TZ_FORCE_EVENT_OST);
    EPWM_forceTripZoneEvent(CLC_SEC_LEG1_PWM_BASE, EPWM_TZ_FORCE_EVENT_OST);
}

void clc_HAL_setBdVoutProtect(void)
{
#if CLC_BOARD_PROTECTION_VSEC

    GPIO_setDirectionMode(56, GPIO_DIR_MODE_IN);
    GPIO_setQualificationMode(56, GPIO_QUAL_SYNC);
    GPIO_setPinConfig(GPIO_56_GPIO56);
    // Configure Input-XBAR INPUT1 to GPIO12
    XBAR_setInputPin(XBAR_INPUT1, 56);

#else

#endif
}
